### ISSUE TITLE
Error: MarkoNotionExt has no attribute parser_mixins

### ISSUE THREAD

**Issue by jek-ml-lab** [zhaowb/notion-params#1]
I found that your code doesn't work with Marko version 2.0.3. I had to downgrade Marko version to 1.2.0.

The following error get reported:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 from notion_params import NotionParams as NP

File ~/Documents/.../code/notion_params/__init__.py:3
      1 from typing import Any, List, Mapping
----> 3 from .markdown import md, md_line
      4 from .client import Client
      7 class NotionParams:

File ~/Documents/.../code/notion_params/markdown.py:367
    358     elements = [
    359         marko.ext.gfm.elements.Paragraph,
    360         marko.ext.gfm.elements.Strikethrough,
   (...)
    363         marko.ext.gfm.elements.TableCell,
    364     ]
    366 _md = marko.Markdown(marko.Parser, MarkoNotionRenderer)
--> 367 _md.use(MarkoNotionExt)
    369 def md(text):
    370     result = _md(text)

File ~/anaconda3/envs/.../lib/python3.11/site-packages/marko/__init__.py:87, in Markdown.use(self, *extensions)
     84 if isinstance(extension, str):
     85     extension = load_extension(extension)
---> 87 self._parser_mixins = extension.parser_mixins + self._parser_mixins
     88 self._renderer_mixins = extension.renderer_mixins + self._renderer_mixins
     89 self._extra_elements.extend(extension.elements)

AttributeError: type object 'MarkoNotionExt' has no attribute 'parser_mixins'
```
